pipeline {
    agent any
    tools{
       def mvnHome =  maven 'Maven'
    }
    stages {
        stage('SCM Checkout') {
            git 'https://github.com/EDSONCORVO7/AutomationJenkins.git'
        }
        
        stage('Build') {
            git 'https://github.com/EDSONCORVO7/AutomationJenkins.git'
            sh "${mvnHome}/bin/mvn package"
        }
    }
    
}
