node{
	stage('SCM Checkout'){
		git 'https://github.com/EDSONCORVO7/AutomationJenkins.git'
	}
	stage('test'){
		step{
			dir("TestCasesAutomation")
			sh "mvn clean compile test"
		}
		
		}
		stage('Build appliction'){
		step{
			
			echo "mvn clean install -Dmaven.test.skip-true"
		}
		
	}
 }

